version: '3'
services:
  mysql:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./mysql-data:/var/lib/mysql"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - mysql
    working_dir: "/app"